[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  fail_build = false


[[headers]]
  for = "*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "attachment"
    Cache-Control = "public, max-age=0, must-revalidate" 