[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "attachment"
    Cache-Control = "public, max-age=0, must-revalidate" 